from __future__ import annotations
import os
import re
import json
import shlex
import textwrap
import argparse
from pathlib import Path
from datetime import datetime

OUTPUT_DIR = Path("generated_tests")
OUTPUT_DIR.mkdir(exist_ok=True)

SAFE_NAME_RE = re.compile(r"[^\w]+")   

def _sanitise(name: str) -> str:
    """Turn an arbitrary string into a Python/Robot-safe identifier."""
    return SAFE_NAME_RE.sub("_", name).strip("_").lower()

PYTEST_TEMPLATE = '''\
"""
Auto-generated by SecCodeGPT test_generator.py
Tool        : {tool}
Target      : {target}
Generated at: {timestamp}

Run with:
    pytest {filename} -v
"""

import subprocess
import json
import pytest

@pytest.fixture(scope="module")
def run_result():
    """Execute the security command and expose its output to all tests."""
    cmd = {cmd_repr}
    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        timeout={timeout},
    )
    return result

class Test{class_name}:

    def test_exit_code(self, run_result):
        """Command must exit cleanly (return code 0)."""
        assert run_result.returncode == 0, (
            f"Expected exit code 0, got {{run_result.returncode}}\\n"
            f"stderr: {{run_result.stderr[:500]}}"
        )

    def test_stdout_not_empty(self, run_result):
        """Command must produce non-empty stdout."""
        assert run_result.stdout.strip(), "Command produced no output on stdout."

    def test_no_critical_errors(self, run_result):
        """Stderr must not contain critical failure indicators."""
        critical_patterns = ["CRITICAL", "Segmentation fault", "Traceback (most recent call last)"]
        for pattern in critical_patterns:
            assert pattern not in run_result.stderr, (
                f"Critical error pattern '{{pattern}}' found in stderr:\\n{{run_result.stderr[:500]}}"
            )

{extra_tests}
'''

PYTEST_JSON_EXTRA = '''\
    def test_output_is_valid_json(self, run_result):
        """Command output must be parseable as JSON."""
        try:
            data = json.loads(run_result.stdout)
            assert isinstance(data, (dict, list)), "JSON root must be an object or array."
        except json.JSONDecodeError as exc:
            pytest.fail(f"Output is not valid JSON: {exc}")
'''

PYTEST_KEYWORD_EXTRA = '''\
    def test_expected_keywords_present(self, run_result):
        """Expected keywords must appear in the combined output."""
        expected_keywords = {keywords!r}
        combined = run_result.stdout + run_result.stderr
        for kw in expected_keywords:
            assert kw.lower() in combined.lower(), (
                f"Expected keyword '{{kw}}' not found in output."
            )
'''


def generate_pytest(
    tool: str,
    command: list[str],
    target: str,
    timeout: int = 60,
    assert_json: bool = False,
    expected_keywords: list[str] | None = None,
) -> Path:
    """
    Write a pytest file for the given security command.

    Returns:
        Path to the generated .py file.
    """
    name      = _sanitise(f"{tool}_{target}")
    timestamp = datetime.utcnow().isoformat(timespec="seconds") + "Z"
    filename  = f"test_{name}.py"
    filepath  = OUTPUT_DIR / filename

    extra_tests = ""
    if assert_json:
        extra_tests += PYTEST_JSON_EXTRA
    if expected_keywords:
        extra_tests += PYTEST_KEYWORD_EXTRA.format(keywords=expected_keywords)

    content = PYTEST_TEMPLATE.format(
        tool=tool,
        target=target,
        timestamp=timestamp,
        filename=filename,
        cmd_repr=repr(command),
        timeout=timeout,
        class_name="".join(w.capitalize() for w in name.split("_")),
        extra_tests=extra_tests,
    )

    filepath.write_text(content, encoding="utf-8")
    print(f"[test_generator] pytest → {filepath}")
    return filepath



ROBOT_TEMPLATE = '''\
*** Settings ***
Documentation     Auto-generated by SecCodeGPT test_generator.py
...               Tool: {tool} | Target: {target} | Generated: {timestamp}
Library           Process
Library           OperatingSystem
Library           Collections

*** Variables ***
${{TARGET}}          {target}
${{TIMEOUT}}         {timeout}s
@{{CMD}}             {cmd_list}

*** Test Cases ***

{tool_title} Exits Successfully
    [Documentation]    {tool} must complete without a non-zero exit code.
    ${{result}}=        Run Process    @{{CMD}}    timeout=${{TIMEOUT}}    stderr=STDOUT
    Should Be Equal As Integers    ${{result.rc}}    0
    ...    msg={tool} returned non-zero exit code: ${{result.rc}}\\nOutput: ${{result.stdout[:500]}}

{tool_title} Produces Output
    [Documentation]    {tool} must produce non-empty stdout.
    ${{result}}=        Run Process    @{{CMD}}    timeout=${{TIMEOUT}}    stderr=STDOUT
    Should Not Be Empty    ${{result.stdout}}    msg={tool} produced no output.

{tool_title} No Critical Errors In Stderr
    [Documentation]    Stderr must not contain CRITICAL or Segmentation fault.
    ${{result}}=        Run Process    @{{CMD}}    timeout=${{TIMEOUT}}    stderr=STDOUT
    Should Not Contain    ${{result.stdout}}    CRITICAL
    Should Not Contain    ${{result.stdout}}    Segmentation fault

{extra_cases}

*** Keywords ***

Run {tool_title}
    [Documentation]    Helper: run the command and return the result object.
    ${{result}}=    Run Process    @{{CMD}}    timeout=${{TIMEOUT}}    stderr=STDOUT
    [Return]        ${{result}}
'''

ROBOT_KEYWORD_EXTRA = '''\
{tool_title} Contains Expected Keywords
    [Documentation]    All expected keywords must appear in the output.
    ${{result}}=        Run Process    @{{CMD}}    timeout=${{TIMEOUT}}    stderr=STDOUT
    FOR    ${{kw}}    IN    {keywords_str}
        Should Contain    ${{result.stdout}}    ${{kw}}
        ...    msg=Expected keyword '${{kw}}' not found in {tool} output.
    END
'''


def generate_robot(
    tool: str,
    command: list[str],
    target: str,
    timeout: int = 60,
    expected_keywords: list[str] | None = None,
) -> Path:
    """
    Write a Robot Framework .robot file for the given security command.

    Returns:
        Path to the generated .robot file.
    """
    name       = _sanitise(f"{tool}_{target}")
    timestamp  = datetime.utcnow().isoformat(timespec="seconds") + "Z"
    filename   = f"{name}.robot"
    filepath   = OUTPUT_DIR / filename
    tool_title = tool.capitalize()

    cmd_list = "\n...               ".join(shlex.quote(t) for t in command)

    extra_cases = ""
    if expected_keywords:
        keywords_str = "    ".join(f"'{kw}'" for kw in expected_keywords)
        extra_cases  = ROBOT_KEYWORD_EXTRA.format(
            tool_title=tool_title,
            keywords_str=keywords_str,
        )

    content = ROBOT_TEMPLATE.format(
        tool=tool,
        tool_title=tool_title,
        target=target,
        timestamp=timestamp,
        cmd_list=cmd_list,
        timeout=timeout,
        extra_cases=extra_cases,
    )

    filepath.write_text(content, encoding="utf-8")
    print(f"[test_generator] robot → {filepath}")
    return filepath

class TestGeneratorRequest:
    """Structured request object consumed by app.py."""

    def __init__(
        self,
        tool: str,
        target: str,
        framework: str = "pytest",          # "pytest" | "robot"
        extra_args: list[str] | None = None,
        timeout: int = 60,
        assert_json: bool = False,
        expected_keywords: list[str] | None = None,
    ):
        self.tool               = tool
        self.target             = target
        self.framework          = framework.lower()
        self.extra_args         = extra_args or []
        self.timeout            = timeout
        self.assert_json        = assert_json
        self.expected_keywords  = expected_keywords or []


def build_command(req: TestGeneratorRequest) -> list[str]:
    """
    Map a tool name + target to a concrete shell command list.
    Only safe, non-destructive options are used here.

    Extend this dict to support more tools.
    """
    TOOL_TEMPLATES: dict[str, list[str]] = {
        "nmap":    ["nmap", "-sV", "--open", "-T4", req.target],
        "nuclei":  ["nuclei", "-u", req.target, "-silent"],
        "sqlmap":  ["sqlmap", "-u", req.target, "--batch", "--level=1", "--risk=1"],
        "nikto":   ["nikto", "-h", req.target],
        "curl":    ["curl", "-s", "-o", "/dev/null", "-w", "%{http_code}", req.target],
    }
    base = TOOL_TEMPLATES.get(req.tool, [req.tool, req.target])
    return base + req.extra_args


def dispatch(req: TestGeneratorRequest) -> dict:
    """
    Generate the appropriate test file and return metadata.

    Returns:
        dict with keys: framework, filepath, content
    """
    command = build_command(req)

    if req.framework == "pytest":
        path = generate_pytest(
            tool=req.tool,
            command=command,
            target=req.target,
            timeout=req.timeout,
            assert_json=req.assert_json,
            expected_keywords=req.expected_keywords,
        )
    elif req.framework == "robot":
        path = generate_robot(
            tool=req.tool,
            command=command,
            target=req.target,
            timeout=req.timeout,
            expected_keywords=req.expected_keywords,
        )
    else:
        raise ValueError(f"Unknown framework: {req.framework!r}. Choose 'pytest' or 'robot'.")

    return {
        "framework": req.framework,
        "filepath":  str(path),
        "content":   path.read_text(encoding="utf-8"),
        "command":   command,
    }

def main():
    parser = argparse.ArgumentParser(description="SecCodeGPT: Automation Test Generator CLI")
    parser.add_argument("--tool",       required=True, help="Security tool name (nmap, nuclei, …)")
    parser.add_argument("--target",     required=True, help="Target host / URL")
    parser.add_argument("--framework",  default="pytest", choices=["pytest", "robot"])
    parser.add_argument("--timeout",    type=int, default=60)
    parser.add_argument("--json",       action="store_true", help="Assert JSON output")
    parser.add_argument("--keywords",   nargs="*", default=[], help="Keywords to assert in output")
    args = parser.parse_args()

    req = TestGeneratorRequest(
        tool=args.tool,
        target=args.target,
        framework=args.framework,
        timeout=args.timeout,
        assert_json=args.json,
        expected_keywords=args.keywords,
    )
    result = dispatch(req)
    print(f"\n[CLI] Generated {result['framework']} test → {result['filepath']}")
    print("-" * 60)
    print(result["content"])


if __name__ == "__main__":
    main()